# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/constellation

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
        
      # run tests!
      - run: cat /dev/null | sbt test:test

  publish:
    machine:
      docker_layer_caching: true
      services:
        - docker

    working_directory: ~/constellation

    # For gcloud https://circleci.com/docs/1.0/google-cloud-platform/
    pre:
      - pyenv global 2.7.12
      - sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
      - sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update kubectl
      - echo $GCLOUD_SERVICE_KEY > ${HOME}/account-auth.json
      - sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
      - sudo /opt/google-cloud-sdk/bin/gcloud config set project $GOOGLE_PROJECT_ID
      - sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set container/cluster $GOOGLE_CLUSTER_NAME
      # Reading the zone from the env var is not working so we set it here
      - sudo /opt/google-cloud-sdk/bin/gcloud config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      IMAGE_REPO: constellationlabs
      # This doesn't work but its directly from their examples...?
      #SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: sbt docker:publishLocal

workflows:
  version: 2
  build:
    jobs:
      - build
  publish:
    jobs:
  #    - build
      - publish:
   #       requires:
   #         - build
          filters:
            branches:
              only: rg-udp-ci