apiVersion: v1
kind: Service
metadata:
  labels:
    app: udp-node-service
  name: udp-node-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 16180
    targetPort: 16180
    name: udp
    protocol: UDP
 # clusterIP: None
  selector:
    run: constellation-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rpc-node-service
  name: rpc-node-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 9000
    name: rpc
    targetPort: 9000
  selector:
    run: constellation-app
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: constellation-app
spec:
  serviceName: rpc-node-service
  serviceName: udp-node-service
  replicas: 1
  template:
    metadata:
      labels:
        run: constellation-app
    spec:
      containers:
      - name: constellation-app
        image: gcr.io/esoteric-helix-197319/constellationlabs/constellation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          hostPort: 9000
          name: rpc
        - containerPort: 2551
          hostPort: 2551
          name: p2p
        - containerPort: 16180
          hostPort: 16180
          name: udp
          protocol: UDP
        env:
        - name: AKKA_ACTOR_SYSTEM_NAME
          value: constellation
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_REMOTING_BIND_HOST
          value: "$HOSTNAME"
        - name: AKKA_SEED_NODE_PORT
          value: '2551'
        - name: HTTP_HOST
          value: 0.0.0.0
        - name: HTTP_PORT
          value: '9000'
        readinessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 30
          timeoutSeconds: 30
