apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-service-cservicename
  name: node-service-cservicename
spec:
  ports:
  - port: 2551
    name: p2p
    targetPort: 2551
  - port: 9000
    name: rpc
    targetPort: 9000
  clusterIP: None
  selector:
    app: constellation-cappname
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: constellation-cappname
spec:
  serviceName: node-service-cservicename
  replicas: 3
  template:
    metadata:
      labels:
        app: constellation-cservicename
    spec:
      containers:
      - name: constellation-cappname
        image: gcr.io/esoteric-helix-197319/constellationlabs/constellation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          hostPort: 9000
          name: rpc
        - containerPort: 2551
          hostPort: 2551
          name: p2p
        env:
        - name: AKKA_ACTOR_SYSTEM_NAME
          value: constellation
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_REMOTING_BIND_HOST
          value: "$HOSTNAME"
        - name: AKKA_SEED_NODE_PORT
          value: '2551'
        - name: HTTP_HOST
          value: 0.0.0.0
        - name: HTTP_PORT
          value: '9000'
        readinessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 30
          timeoutSeconds: 30
